name: CI

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build-signaling-server:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Create env file
        run: |
          cat << EOF > ./signaling-server/app/.env
          PORT=${{ secrets.HEROKU_SIG_SERV1_PORT }}
          CLIENT_ORIGINS=${{ secrets.HEROKU_SIG_SERV1_CLIENT_ORIGINS }}
          MONGO_USERNAME=${{ secrets.HEROKU_SIG_SERV1_MONGO_USERNAME }}
          MONGO_PASSWORD=${{ secrets.HEROKU_SIG_SERV1_MONGO_PASSWORD }}
          MONGO_CLUSTERNAME=${{ secrets.HEROKU_SIG_SERV1_MONGO_CLUSTERNAME }}
          MONGO_DBNAME=${{ secrets.HEROKU_SIG_SERV1_MONGO_DBNAME }}
          EOF

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_SIGNALING_SERVER_1 }}
          appdir: "signaling-server/app"
          usedocker: true
          docker_heroku_process_type: web
